#!/bin/bash

./whistler samples/othat.wav -12 pad test_pad.wav
./whistler samples/othat.wav -12 pluck test_pluck.wav
./whistler samples/othat.wav -12 brass test_brass.wav
./whistler samples/othat.wav -12 flute test_flute.wav
./whistler samples/othat.wav -12 strings test_strings.wav
./whistler samples/othat.wav -12 organ test_organ.wav
./whistler samples/othat.wav -12 bell test_bell.wav
./whistler samples/othat.wav -12 bass test_bass.wav
./whistler samples/othat.wav -12 wurlitzer test_wurlitzer.wav
./whistler samples/othat.wav -12 acid test_acid.wav